export const sportEmojiMap: { [key: string]: string } = {
  Football: "⚽",
  Basketball: "🏀",
  Tennis: "🎾",
  "American Football": "🏈",
  Baseball: "⚾",
  Soccer: "⚽",
  Hockey: "🏒",
  "Ice Hockey": "🏒",
  Golf: "⛳",
  MMA: "🥊",
  Boxing: "🥊",
  F1: "🏎️",
  "Horse Racing": "🏇",
  "E-Sports": "🎮",
};
